### PR TITLE
fixing JSON Object "authenticationDatabase" thrown a NullPointerException

### PR DESCRIPTION
**Pull request by mcNETDev**
When "authenticationDatabase" is not set we must create a new JSONObject.

### CODE REVIEW

**Comment by tomsik68** [comment]
Thanks for the PR!  From what I understand, this fixes a situation when the JSON file exists, but doesn't have "authenticationDatabase" tag. Is that correct or were there different situations where it threw the NPE?

**Comment by mcNETDev** [comment]
Yes that is correct.
I am Planning to do a Forge implementation, that we can install and run Minecraft with forge. Is this okay? Would you accept these changes?

**Comment by Safranil** [comment]
Hi,

I'm interested for these changes, I need to develop a launcher with a update system. I can help if needed and I can develop the update part for mods and configs if you want :smiley:

**Comment by tomsik68** [comment]
@mcNETDev I'll be happy to accept your changes if the API will be used correctly and I'll feel your changes fit in the API appropriately :) I created a gitter channel, so you can catch me sometime if you're unsure how to implement a certain thing ;)

**Pull request merged**
